import networkx as nx
import matplotlib.pyplot as plt
from tqdm import tqdm
from random import choices, seed  # Import 'choices' and 'seed'

def generate_ba_network(n, m0, m, random_seed=None):
    """
    Generate a scale-free network using the Barabási–Albert model.
    
    Parameters:
        n (int): Total number of nodes in the final network.
        m0 (int): Number of nodes in the initial connected network.
        m (int): Number of edges to attach from a new node to existing nodes.
        random_seed (int, optional): Seed for reproducibility. Defaults to None.
        
    Returns:
        G (networkx.Graph): Generated scale-free network.
    """
    # Set the random seed for reproducibility
    if random_seed is not None:
        seed(random_seed)  # Fix the seed for Python's random module

    # Step 1: Initialize a fully connected graph with m0 nodes
    G = nx.complete_graph(m0)
    
    # Step 2: Add new nodes one by one
    for new_node in tqdm(range(m0, n), desc="Adding nodes"):
        # Calculate degrees of existing nodes
        degrees = [G.degree(node) for node in G.nodes()]
        total_degree = sum(degrees)
        
        # Preferential attachment: Probability proportional to degree
        probabilities = [deg / total_degree for deg in degrees]
        
        # Select m nodes to connect to based on probabilities
        targets = list(range(len(G.nodes())))
        selected_nodes = []
        while len(selected_nodes) < m:
            chosen_node = choices(targets, probabilities)[0]
            if chosen_node not in selected_nodes:
                selected_nodes.append(chosen_node)
        
        # Add edges between the new node and selected nodes
        for target in selected_nodes:
            G.add_edge(new_node, target)
    
    return G

# Parameters for the BA model
total_nodes = 10000  # Final number of nodes
initial_nodes = 100  # Initial number of nodes (m0)
edges_per_new_node = 5  # Number of edges added per new node (m)
fixed_seed = 42  # Fixed random seed for reproducibility

# Generate the scale-free network
scale_free_network = generate_ba_network(total_nodes, initial_nodes, edges_per_new_node, random_seed=fixed_seed)

# Visualize the generated graph
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(scale_free_network, seed=fixed_seed)  # Use the same seed for layout
nx.draw(scale_free_network, pos, node_size=10, node_color='blue', edge_color='gray', alpha=0.5, with_labels=False)
plt.title("Scale-Free Network Generated by Barabási–Albert Model")
plt.show()




# Reuse the same centrality analysis function
def centrality_analysis(G, label="Network"):
    import numpy as np
    print(f"\n📊 Centrality Measures for {label}")

    # 1. Degree Centrality
    degree_centrality = nx.degree_centrality(G)
    
    # 2. Betweenness Centrality
    print("Computing Betweenness Centrality...")
    betweenness_centrality = nx.betweenness_centrality(G)
    
    # 3. Closeness Centrality
    closeness_centrality = nx.closeness_centrality(G)
    
    # 4. Eigenvector Centrality
    print("Computing Eigenvector Centrality...")
    eigenvector_centrality = nx.eigenvector_centrality(G, max_iter=1000)

    centralities = {
        "Degree": degree_centrality,
        "Betweenness": betweenness_centrality,
        "Closeness": closeness_centrality,
        "Eigenvector": eigenvector_centrality
    }

    # Summary Stats and Plots
    for name, cent in centralities.items():
        values = list(cent.values())
        print(f"\n--- {name} Centrality ---")
        print(f"Mean: {np.mean(values):.4f}")
        print(f"Std Dev: {np.std(values):.4f}")
        print(f"Max: {np.max(values):.4f}")
        print(f"Min: {np.min(values):.4f}")
        top_nodes = sorted(cent.items(), key=lambda x: x[1], reverse=True)[:5]
        print(f"Top 5 Nodes:")
        for node, val in top_nodes:
            print(f"Node {node} → {val:.4f}")

        # Plot distribution
        plt.figure(figsize=(8, 5))
        plt.hist(values, bins=50, color='lightcoral', edgecolor='black', alpha=0.75)
        plt.title(f"{name} Centrality Distribution - {label}")
        plt.xlabel("Centrality Score")
        plt.ylabel("Frequency")
        plt.grid(True)
        plt.tight_layout()
        plt.show()

# Run it on scale_free_network
centrality_analysis(scale_free_network, label="S (Scale-Free Network)")
