import networkx as nx
import matplotlib.pyplot as plt
from tqdm import tqdm
from random import choices, seed  # Import 'choices' and 'seed'

def generate_ba_network(n, m0, m, random_seed=None):
    """
    Generate a scale-free network using the Barabási–Albert model.
    
    Parameters:
        n (int): Total number of nodes in the final network.
        m0 (int): Number of nodes in the initial connected network.
        m (int): Number of edges to attach from a new node to existing nodes.
        random_seed (int, optional): Seed for reproducibility. Defaults to None.
        
    Returns:
        G (networkx.Graph): Generated scale-free network.
    """
    # Set the random seed for reproducibility
    if random_seed is not None:
        seed(random_seed)  # Fix the seed for Python's random module

    # Step 1: Initialize a fully connected graph with m0 nodes
    G = nx.complete_graph(m0)
    
    # Step 2: Add new nodes one by one
    for new_node in tqdm(range(m0, n), desc="Adding nodes"):
        # Calculate degrees of existing nodes
        degrees = [G.degree(node) for node in G.nodes()]
        total_degree = sum(degrees)
        
        # Preferential attachment: Probability proportional to degree
        probabilities = [deg / total_degree for deg in degrees]
        
        # Select m nodes to connect to based on probabilities
        targets = list(range(len(G.nodes())))
        selected_nodes = []
        while len(selected_nodes) < m:
            chosen_node = choices(targets, probabilities)[0]
            if chosen_node not in selected_nodes:
                selected_nodes.append(chosen_node)
        
        # Add edges between the new node and selected nodes
        for target in selected_nodes:
            G.add_edge(new_node, target)
    
    return G

# Parameters for the BA model
total_nodes = 10000  # Final number of nodes
initial_nodes = 100  # Initial number of nodes (m0)
edges_per_new_node = 5  # Number of edges added per new node (m)
fixed_seed = 42  # Fixed random seed for reproducibility

# Generate the scale-free network
scale_free_network = generate_ba_network(total_nodes, initial_nodes, edges_per_new_node, random_seed=fixed_seed)

# Visualize the generated graph
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(scale_free_network, seed=fixed_seed)  # Use the same seed for layout
nx.draw(scale_free_network, pos, node_size=10, node_color='blue', edge_color='gray', alpha=0.5, with_labels=False)
plt.title("Scale-Free Network Generated by Barabási–Albert Model")
plt.show()